name: Build and Push Docker Image

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.27.2'  # Adjust to your EKS version

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig --name sandbox-eks

      - name: Deploy Kaniko Job
        run: |
          kubectl apply -f kaniko-job.yaml

      - name: Wait for Kaniko Job to Complete
        run: |
          kubectl wait --for=condition=Ready pod -l job-name=kaniko-build --timeout=30m || exit 1    

      - name: Check Kaniko Pod Status and Handle Errors
        run: |
          POD_NAME=$(kubectl get pods --selector=job-name=kaniko-build --output=jsonpath='{.items[0].metadata.name}')
          POD_STATUS=$(kubectl get pod $POD_NAME --output=jsonpath='{.status.phase}')
          
          if [ "$POD_STATUS" == "Failed" ] || [ "$POD_STATUS" == "CrashLoopBackOff" ]; then
            echo "Kaniko Pod is in error state: $POD_STATUS"
            echo "Fetching logs before killing the job..."
            kubectl logs $POD_NAME
            echo "Killing the Kaniko job due to pod failure..."
            kubectl delete job kaniko-build
            exit 1
          else
            echo "Kaniko Pod is running successfully: $POD_STATUS"
          fi

      # Fetch Kaniko Build Logs (only if the job succeeds)
      - name: Fetch Kaniko Build Logs and Check for Errors
        run: |
          POD_NAME=$(kubectl get pods --selector=job-name=kaniko-build --output=jsonpath='{.items[0].metadata.name}')
          LOGS=$(kubectl logs $POD_NAME)
          echo "$LOGS"
          if echo "$LOGS" | grep -i "error"; then
             echo "Error found in Kaniko build logs."
             exit 1
          else
             echo "No errors found in Kaniko build logs."
          fi


      - name: Clean up Kaniko Job
        run: |
          kubectl delete job kaniko-build
